import { ScenarioPreset } from '../types/simulation';

export const SCENARIO_PRESETS: ScenarioPreset[] = [
  // LAB 1: Process Types & Valve Diagnostics
  {
    id: 'lab1-self-regulating',
    name: 'Self-Regulating Process (Normal)',
    labId: 'lab1',
    description: 'Textbook self-regulating process (Figure 2 & 5). Responds to a manual CO step by settling at a new stable PV.',
    process: {
      type: 'self-regulating',
      Kp: 1.5,
      tau1: 0.56,
      tauD: 0.15,
      Ki: 0,
      runawayAlpha: 0,
      initialPV: 50,
      ambientPV: 50,
      tauSensor: 0.02,
      noiseRms: 0.2,
      stiction: 0,
    },
    controller: {
      mode: 'MANUAL',
      Kc: 1.0,
      Ti: 0.5,
      Td: 0,
      bias: 40,
      coMin: 0,
      coMax: 100,
      propOnPV: false,
      derivOnPV: false,
      spSofteningTau: 0,
      transmitterFilterTau: 0.01,
    },
    targetSP: 50,
  },
  {
    id: 'lab1-integrating',
    name: 'Integrating Process (Liquid Level)',
    labId: 'lab1',
    description: 'Vessel liquid level with constant outflow (Figure 3 & 6). CO step causes continuous ramp until limits; non-self-regulating.',
    process: {
      type: 'integrating',
      Kp: 0,
      tau1: 0.2,
      tauD: 0.1,
      Ki: 2.0,
      runawayAlpha: 0,
      initialPV: 50,
      ambientPV: 50,
      tauSensor: 0.02,
      noiseRms: 0.3,
      stiction: 0,
    },
    controller: {
      mode: 'MANUAL',
      Kc: 1.5,
      Ti: 5.0,
      Td: 0,
      bias: 40,
      coMin: 0,
      coMax: 100,
      propOnPV: false,
      derivOnPV: false,
      spSofteningTau: 0,
      transmitterFilterTau: 0.02,
    },
    targetSP: 50,
  },
  {
    id: 'lab1-runaway',
    name: 'Runaway Exothermic Reactor',
    labId: 'lab1',
    description: 'Exothermic reaction where heat output accelerates with temperature (Figure 4). Inherently unstable without rapid derivative action.',
    process: {
      type: 'runaway',
      Kp: 1.2,
      tau1: 0.6,
      tauD: 0.12,
      Ki: 0,
      runawayAlpha: 0.85, // strong positive thermal feedback
      initialPV: 50,
      ambientPV: 50,
      tauSensor: 0.05,
      noiseRms: 0.3,
      stiction: 0,
    },
    controller: {
      mode: 'PID',
      Kc: 3.5,
      Ti: 1.2,
      Td: 0.28,
      bias: 40,
      coMin: 0,
      coMax: 100,
      propOnPV: false,
      derivOnPV: true,
      spSofteningTau: 0,
      transmitterFilterTau: 0.02,
    },
    targetSP: 50,
  },
  {
    id: 'lab1-stiction-manual',
    name: 'Valve Stiction (Manual Bump Test)',
    labId: 'lab1',
    description: 'Excessive stem packing friction in manual mode (Figure 7). PV does not return to the same value for the same CO due to deadband.',
    process: {
      type: 'self-regulating',
      Kp: 1.5,
      tau1: 0.56,
      tauD: 0.15,
      Ki: 0,
      runawayAlpha: 0,
      initialPV: 50,
      ambientPV: 50,
      tauSensor: 0.02,
      noiseRms: 0.2,
      stiction: 4.5, // 4.5% stiction deadband
    },
    controller: {
      mode: 'MANUAL',
      Kc: 1.0,
      Ti: 0.5,
      Td: 0,
      bias: 40,
      coMin: 0,
      coMax: 100,
      propOnPV: false,
      derivOnPV: false,
      spSofteningTau: 0,
      transmitterFilterTau: 0.01,
    },
    targetSP: 50,
  },
  {
    id: 'lab1-stiction-auto',
    name: 'Valve Stiction in Automatic (Sawtooth Limit Cycle)',
    labId: 'lab1',
    description: 'Figure 8: Integral action ramps CO in a sawtooth wave while the valve sticks, then suddenly jumps past SP creating perpetual cycling.',
    process: {
      type: 'self-regulating',
      Kp: 1.5,
      tau1: 0.56,
      tauD: 0.15,
      Ki: 0,
      runawayAlpha: 0,
      initialPV: 50,
      ambientPV: 50,
      tauSensor: 0.02,
      noiseRms: 0.2,
      stiction: 4.0,
    },
    controller: {
      mode: 'PI',
      Kc: 1.8,
      Ti: 0.4,
      Td: 0,
      bias: 40,
      coMin: 0,
      coMax: 100,
      propOnPV: false,
      derivOnPV: false,
      spSofteningTau: 0,
      transmitterFilterTau: 0.01,
    },
    targetSP: 50,
  },

  // LAB 2: Robustness & Criteria
  {
    id: 'lab2-quarter-decay',
    name: 'Quarter Amplitude Decay (Aggressive)',
    labId: 'lab2',
    description: 'Figures 9, 14: Decay ratio DR = 0.25 (1/4 amp decay). Fast settling but high overshoot and >60% manipulated variable CO swing.',
    process: {
      type: 'self-regulating',
      Kp: 1.5,
      tau1: 0.56,
      tauD: 0.15,
      Ki: 0,
      runawayAlpha: 0,
      initialPV: 50,
      ambientPV: 50,
      tauSensor: 0.02,
      noiseRms: 0.1,
      stiction: 0,
    },
    controller: {
      mode: 'PI',
      Kc: 3.3,
      Ti: 0.50,
      Td: 0,
      bias: 40,
      coMin: 0,
      coMax: 100,
      propOnPV: false,
      derivOnPV: false,
      spSofteningTau: 0,
      transmitterFilterTau: 0.01,
    },
    targetSP: 60,
  },
  {
    id: 'lab2-zero-overshoot',
    name: 'Zero Overshoot / Critically Damped (Gentle)',
    labId: 'lab2',
    description: 'Figures 11, 15: Overdamped/critically damped response. Zero overshoot, minor CO changes (<10%), zero valve cycling, maximum downstream friendliness.',
    process: {
      type: 'self-regulating',
      Kp: 1.5,
      tau1: 0.56,
      tauD: 0.15,
      Ki: 0,
      runawayAlpha: 0,
      initialPV: 50,
      ambientPV: 50,
      tauSensor: 0.02,
      noiseRms: 0.1,
      stiction: 0,
    },
    controller: {
      mode: 'PI',
      Kc: 0.29,
      Ti: 0.56,
      Td: 0,
      bias: 40,
      coMin: 0,
      coMax: 100,
      propOnPV: false,
      derivOnPV: false,
      spSofteningTau: 0,
      transmitterFilterTau: 0.01,
    },
    targetSP: 60,
  },

  // LAB 3 & 4: Benchmarks
  {
    id: 'lab3-benchmark1-standard',
    name: 'ILM Benchmark 1: Standard Process (Up = 0.27)',
    labId: 'lab3',
    description: 'Figures 22-27, Table 4: tauD = 0.15 min, tau1 = 0.56 min, Kp = 1.5. Within ZN sweet spot (0.1 to 0.5).',
    process: {
      type: 'self-regulating',
      Kp: 1.5,
      tau1: 0.56,
      tauD: 0.15,
      Ki: 0,
      runawayAlpha: 0,
      initialPV: 50,
      ambientPV: 50,
      tauSensor: 0.02,
      noiseRms: 0.15,
      stiction: 0,
    },
    controller: {
      mode: 'PI',
      Kc: 3.3,
      Ti: 0.50,
      Td: 0,
      bias: 40,
      coMin: 0,
      coMax: 100,
      propOnPV: false,
      derivOnPV: false,
      spSofteningTau: 0,
      transmitterFilterTau: 0.01,
    },
    targetSP: 60,
  },
  {
    id: 'lab3-benchmark2-deadtime',
    name: 'ILM Benchmark 2: High Dead-Time (Up = 0.72)',
    labId: 'lab3',
    description: 'Figures 28-34, Table 5: tauD = 0.23 min, tau1 = 0.32 min, Kp = 1.5. Outside ZN range! ZN causes 1/2 amp decay instability; IMC and Lambda excel.',
    process: {
      type: 'self-regulating',
      Kp: 1.5,
      tau1: 0.32,
      tauD: 0.23,
      Ki: 0,
      runawayAlpha: 0,
      initialPV: 50,
      ambientPV: 50,
      tauSensor: 0.02,
      noiseRms: 0.15,
      stiction: 0,
    },
    controller: {
      mode: 'PI',
      Kc: 1.1, // ZN reaction curve setting that overshoots
      Ti: 0.77,
      Td: 0,
      bias: 40,
      coMin: 0,
      coMax: 100,
      propOnPV: false,
      derivOnPV: false,
      spSofteningTau: 0,
      transmitterFilterTau: 0.01,
    },
    targetSP: 60,
  },

  // LAB 5: Industrial Archetypes
  {
    id: 'lab5-liquid-flow',
    name: 'Liquid Flow / Pressure Loop (FIC-101)',
    labId: 'lab5',
    description: 'Fast acting, noisy PV, Up ≈ 1.0. High dynamic gain requires low Kc (0.3), fast reset (0.1 min/rpt), transmitter filtering, no derivative!',
    process: {
      type: 'self-regulating',
      Kp: 1.8,
      tau1: 0.06, // fast time constant
      tauD: 0.05, // Up = 0.05/0.06 ≈ 0.83
      Ki: 0,
      runawayAlpha: 0,
      initialPV: 50,
      ambientPV: 50,
      tauSensor: 0.01,
      noiseRms: 1.2, // naturally noisy flow
      stiction: 0.5,
    },
    controller: {
      mode: 'PI',
      Kc: 0.3,
      Ti: 0.1,
      Td: 0,
      bias: 40,
      coMin: 0,
      coMax: 100,
      propOnPV: false,
      derivOnPV: false,
      spSofteningTau: 0,
      transmitterFilterTau: 0.05, // 0.5 x scan rate
    },
    targetSP: 50,
  },
  {
    id: 'lab5-vessel-gas-pressure',
    name: 'Gas Vessel Back Pressure (PIC-101)',
    labId: 'lab5',
    description: 'Self-regulating with large tau1 vs tauD (small Up, very easy to control). High proportional gain (Kc = 5.0) and slow reset (5.0 min/rpt).',
    process: {
      type: 'self-regulating',
      Kp: 1.1,
      tau1: 2.5,  // large volume capacity
      tauD: 0.08, // small Up = 0.08/2.5 = 0.032
      Ki: 0,
      runawayAlpha: 0,
      initialPV: 50,
      ambientPV: 50,
      tauSensor: 0.02,
      noiseRms: 0.2,
      stiction: 0,
    },
    controller: {
      mode: 'PI',
      Kc: 5.0,
      Ti: 5.0,
      Td: 0,
      bias: 40,
      coMin: 0,
      coMax: 100,
      propOnPV: false,
      derivOnPV: false,
      spSofteningTau: 0,
      transmitterFilterTau: 0.02,
    },
    targetSP: 50,
  },
  {
    id: 'lab5-furnace-pressure',
    name: 'Furnace Draft / Reactor Pressure',
    labId: 'lab5',
    description: 'Sensitive system with rupture disc hazards. PI with Proportional on PV to avoid controller kick, PV dampening, and gain halved for robustness.',
    process: {
      type: 'self-regulating',
      Kp: 2.2, // high static gain from small span
      tau1: 1.8,
      tauD: 0.15,
      Ki: 0,
      runawayAlpha: 0,
      initialPV: 50,
      ambientPV: 50,
      tauSensor: 0.02,
      noiseRms: 0.8, // noisy draft pressure
      stiction: 0,
    },
    controller: {
      mode: 'PI',
      Kc: 1.2, // halved gain for safety
      Ti: 1.2,
      Td: 0,
      bias: 40,
      coMin: 0,
      coMax: 100,
      propOnPV: true, // Proportional on PV eliminates kick!
      derivOnPV: false,
      spSofteningTau: 0.25, // SP softening prevents rupture disc burst
      transmitterFilterTau: 0.08,
    },
    targetSP: 50,
  },
  {
    id: 'lab5-tight-level',
    name: 'Tight Level Control (LIC-101)',
    labId: 'lab5',
    description: 'Integrating process. Keep PV tightly pinned at SP to preserve mass balance and prevent exposing steam heating coils to avoid fractures and scale.',
    process: {
      type: 'integrating',
      Kp: 0,
      tau1: 0.2,
      tauD: 0.08,
      Ki: 1.5,
      runawayAlpha: 0,
      initialPV: 50,
      ambientPV: 50,
      tauSensor: 0.02,
      noiseRms: 0.5,
      stiction: 0,
    },
    controller: {
      mode: 'PI',
      Kc: 5.0,
      Ti: 10.0,
      Td: 0,
      bias: 40,
      coMin: 0,
      coMax: 100,
      propOnPV: false,
      derivOnPV: false,
      spSofteningTau: 0,
      transmitterFilterTau: 0.04,
    },
    targetSP: 50,
  },
  {
    id: 'lab5-surge-level',
    name: 'Surge (Averaging) Level Control (LIC-101)',
    labId: 'lab5',
    description: 'Buffer vessel with multiple fluctuating streams. Pure P-only control (Kc = 1.0 or 2.0). Major SP deviations allowed to keep outflow silky smooth.',
    process: {
      type: 'integrating',
      Kp: 0,
      tau1: 0.2,
      tauD: 0.08,
      Ki: 1.5,
      runawayAlpha: 0,
      initialPV: 50,
      ambientPV: 50,
      tauSensor: 0.02,
      noiseRms: 0.5,
      stiction: 0,
    },
    controller: {
      mode: 'P',
      Kc: 1.5, // Between 1.0 (100% PB) and 2.0 (50% PB)
      Ti: 50.0, // negligible reset
      Td: 0,
      bias: 40,
      coMin: 0,
      coMax: 100,
      propOnPV: false,
      derivOnPV: false,
      spSofteningTau: 0,
      transmitterFilterTau: 0.04,
    },
    targetSP: 50,
  },
  {
    id: 'lab5-inline-temp',
    name: 'Inline Heat Exchanger Temperature (TIC-101)',
    labId: 'lab5',
    description: 'Thermal storage + thermowell lag. PID with PD on PV, Integral on Error, SP softening, and derivative pre-act to reject cold oil load upsets.',
    process: {
      type: 'self-regulating',
      Kp: 1.4,
      tau1: 1.6,
      tauD: 0.25,
      Ki: 0,
      runawayAlpha: 0,
      initialPV: 50,
      ambientPV: 50,
      tauSensor: 0.4, // thermowell first-order time constant lag
      noiseRms: 0.1,  // clean non-noisy temperature signal
      stiction: 0,
    },
    controller: {
      mode: 'PID',
      Kc: 0.5,
      Ti: 1.0,
      Td: 0.25, // 15 seconds derivative pre-act
      bias: 40,
      coMin: 0,
      coMax: 100,
      propOnPV: false,
      derivOnPV: true, // PD on PV prevents derivative kick!
      spSofteningTau: 0.35, // SP softening counteracts thermowell overshoot
      transmitterFilterTau: 0.02,
    },
    targetSP: 60,
  },
];
